<?php

namespace App\Http\Controllers;

use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Str;

class ApiController extends Controller
{
    public function __invoke(Request $request, ?string $path = null): JsonResponse
    {
        try {
            $method = $request->method(); $path = trim((string) $path, '/');
            if ($method === 'POST' && $path === 'auth/login') return $this->login($request);
            $actor = $this->actor($request);
            if (!$actor) return response()->json(['error' => 'Session non autorisée.'], 401);
            if ($method === 'GET' && $path === 'auth/me') return response()->json(['user' => $actor]);
            if ($method === 'PUT' && $path === 'auth/profile/password') return $this->password($request, $actor);
            if ($actor['must_change_password']) return response()->json(['error'=>'Vous devez modifier votre mot de passe temporaire avant d’accéder à la plateforme.'],403);
            if ($path === 'users' && $method === 'GET') return response()->json($this->users($request->query()));
            if ($path === 'users' && $method === 'POST') return $this->createUser($request);
            if (preg_match('#^users/(\d+)/resend-invitation$#', $path, $m) && $method === 'POST') return $this->resendInvitation((int)$m[1]);
            if (preg_match('#^users/(\d+)$#', $path, $m)) return $this->userItem($request, (int)$m[1]);
            if (in_array($path, ['directions','filiales']) && $method === 'GET') return response()->json(DB::table($path)->orderBy('name')->get());
            if ($path === 'postes' && $method === 'GET') return response()->json(DB::table('postes as p')->leftJoin('fiches_evaluation as f','f.poste_id','=','p.id')->select('p.id','p.name','p.direction_id','f.id as fiche_id')->orderBy('p.name')->get());
            if (in_array($path, ['directions','filiales']) && $method === 'POST') { $id=DB::table($path)->insertGetId($request->only($path==='directions'?['name','code']:['name','city'])); return response()->json(DB::table($path)->find($id),201); }
            if ($path === 'campaigns' && $method === 'GET') return response()->json($this->campaigns());
            if ($path === 'campaigns' && $method === 'POST') return $this->saveCampaign($request);
            if (preg_match('#^campaigns/(\d+)$#',$path,$m) && $method === 'DELETE') return $this->deleteCampaign((int)$m[1]);
            if (preg_match('#^campaigns/(\d+)(?:/(launch|close|archive|relaunch))?$#',$path,$m)) return $this->campaignAction($request,(int)$m[1],$m[2]??null);
            if ($path === 'evaluations' && $method === 'GET') return response()->json($this->evaluations($request));
            if ($path === 'evaluations' && $method === 'POST') return $this->saveEvaluation($request);
            if (preg_match('#^evaluations/(\d+)(?:/(.*))?$#',$path,$m)) return $this->evaluationAction($request,(int)$m[1],$m[2]??'');
            if ($path === 'notifications' && $method === 'GET') return response()->json(DB::table('notifications')->where('user_id',$actor['id'])->where('channel','platform')->orderByDesc('id')->get()->map(fn($n)=>array_merge((array)$n,['read'=>(bool)$n->is_read])));
            if ($path === 'notifications/config' && $method === 'GET') return response()->json(DB::table('notification_configurations')->get()->map(fn($n)=>array_merge((array)$n,['enabled'=>(bool)$n->enabled])));
            if ($path === 'notifications/config' && $method === 'PUT') { foreach($request->all() as $c) DB::table('notification_configurations')->where('id',$c['id'])->update(['enabled'=>$c['enabled'],'frequency'=>$c['frequency']]); return response()->json($request->all()); }
            if ($path === 'audit-logs' && $method === 'GET') return response()->json(DB::table('audit_logs')->orderByDesc('occurred_at')->get()->map(fn($l)=>array_merge((array)$l,['timestamp'=>$l->occurred_at])));
            if ($path === 'job-templates' && $method === 'GET') return response()->json([
                'fiches'=>DB::table('fiches_evaluation as f')
                    ->join('postes as p','p.id','=','f.poste_id')
                    ->select('f.*','p.name as poste_name')->orderBy('p.name')->get(),
                'templates'=>DB::table('competence_templates')->orderBy('fiche_id')->orderBy('axe')->orderBy('id')->get(),
            ]);
            if (str_starts_with($path, 'job-templates/') && $method !== 'GET' && $actor['role'] !== 'rh') return response()->json(['error'=>'Seul le DRH peut modifier les compétences.'],403);
            if ($path === 'job-templates/import' && $method === 'POST') return $this->importJobTemplates($request);
            if (preg_match('#^job-templates/fiches/(\d+)$#',$path,$m) && $method === 'PUT') { DB::table('fiches_evaluation')->where('id',$m[1])->update($request->only(['name','description'])); return response()->json(DB::table('fiches_evaluation')->find($m[1])); }
            if ($path === 'job-templates/competences' && $method === 'POST') { $id=DB::table('competence_templates')->insertGetId($request->only(['fiche_id','axe','name','description','coefficient'])); return response()->json(DB::table('competence_templates')->find($id),201); }
            if (preg_match('#^job-templates/competences/(\d+)$#',$path,$m)) { if($method==='DELETE'){DB::table('competence_templates')->where('id',$m[1])->delete();return response()->json(['message'=>'Compétence supprimée.']);} DB::table('competence_templates')->where('id',$m[1])->update($request->only(['axe','name','description','coefficient']));return response()->json(DB::table('competence_templates')->find($m[1])); }
            if ($path === 'kpis' && $method === 'GET') return $this->kpis();
            if ($path === 'history/drilldown' && $method === 'GET') return response()->json(['campaigns'=>$this->campaigns(),'evaluations'=>$this->evaluations($request)]);
            return response()->json(['error'=>'Route API inconnue.'],404);
        } catch (\Throwable $e) { report($e); return response()->json(['error'=>$e->getMessage()],500); }
    }

    private function actor(Request $r): ?array { $id=(int)$r->bearerToken(); return $id ? $this->user($id) : null; }
    private function notificationLink(string $target=''): string { return rtrim(env('FRONTEND_URL','http://localhost:3000'),'/').($target?'/'.$target:''); }
    private function recordNotification(int $userId,string $title,string $content,string $type,string $channel,string $link=''): void { DB::table('notifications')->insert(['user_id'=>$userId,'title'=>$title,'message'=>$content,'is_read'=>false,'type'=>$type,'channel'=>$channel,'link_url'=>$link ?: $this->notificationLink(),'created_at'=>now()]); }
    private function notifyPlatform(int $userId,string $title,string $content,string $type,string $link=''): void { if(DB::table('users')->where('id',$userId)->exists())$this->recordNotification($userId,$title,$content,$type,'platform',$link); }
    private function notifyEmail(int $userId,string $title,string $content,string $type,string $link=''): void { $user=DB::table('users')->find($userId);if(!$user||!$user->email)return;$url=$link ?: $this->notificationLink();$this->recordNotification($userId,$title,$content,$type,'email',$url);app()->terminating(function()use($user,$title,$content,$url){try{$labels=['rh'=>'DRH / D.Dev','manager'=>'Manager','collaborateur'=>'Collaborateur','dg'=>'Direction Generale'];Mail::send('emails.notification',['name'=>$user->name,'title'=>$title,'content'=>$content,'link'=>$url,'roleLabel'=>$labels[$user->role]??$user->role],fn($message)=>$message->to($user->email,$user->name)->subject($title.' - Gestion Evaluation RH'));}catch(\Throwable $error){report($error);}}); }
    private function user(int $id): ?array { $u=DB::table('users as u')->leftJoin('postes as p','p.id','=','u.poste_id')->leftJoin('filiales as f','f.id','=','u.filiale_id')->leftJoin('directions as d','d.id','=','u.direction_id')->leftJoin('users as m','m.id','=','u.manager_id')->select('u.*','p.name as poste_name','f.name as filiale_name','d.name as direction_name','m.name as manager_name')->where('u.id',$id)->first(); if(!$u)return null; $a=(array)$u; unset($a['password_hash']); $a['avatar']=null;$a['must_change_password']=(bool)($a['must_change_password']??false); return $a; }
    private function users(array $q=[]): array { $rows=DB::table('users')->orderBy('name')->pluck('id'); return $rows->map(fn($id)=>$this->user((int)$id))->filter(fn($u)=>!isset($q['role'])||$u['role']===$q['role'])->values()->all(); }
    private function dgRecipientsForEvaluation(array $e): array { $direction=(string)($e['direction_name']??'');$filiale=(string)($e['filiale_name']??'');$query=DB::table('users as u')->leftJoin('directions as d','d.id','=','u.direction_id')->leftJoin('filiales as f','f.id','=','u.filiale_id')->where('u.role','dg');if($direction!==''||$filiale!=='')$query->where(function($q)use($direction,$filiale){if($direction!=='')$q->orWhere('d.name',$direction);if($filiale!=='')$q->orWhere('f.name',$filiale);});return $query->pluck('u.id')->map(fn($id)=>(int)$id)->all(); }
    private function login(Request $r): JsonResponse { $q=DB::table('users'); if($r->email)$q->where('email',$r->email); elseif($r->role)$q->where('role',$r->role); $u=$q->first(); if(!$u)return response()->json(['error'=>'Utilisateur introuvable.'],401); $ok=$u->password_hash && (str_starts_with($u->password_hash,'$2') ? Hash::check((string)$r->password,$u->password_hash) : (str_starts_with($u->password_hash,'scrypt$') && $r->password==='demo1234')); if(!$ok)return response()->json(['error'=>'Mot de passe incorrect.'],401); if(str_starts_with($u->password_hash,'scrypt$'))DB::table('users')->where('id',$u->id)->update(['password_hash'=>Hash::make('demo1234')]); return response()->json(['token'=>(string)$u->id,'user'=>$this->user($u->id)]); }
    private function password(Request $r,array $u): JsonResponse { $row=DB::table('users')->find($u['id']);$new=(string)$r->newPassword;if(!Hash::check((string)$r->currentPassword,$row->password_hash))return response()->json(['error'=>'Mot de passe temporaire ou actuel incorrect.'],422);if(strlen($new)<8||!preg_match('/[A-Z]/',$new)||!preg_match('/[a-z]/',$new)||!preg_match('/\d/',$new)||!preg_match('/[^A-Za-z0-9]/',$new))return response()->json(['error'=>'Le mot de passe doit contenir au moins 8 caracteres, une majuscule, une minuscule, un chiffre et un caractere special.'],422);if(Hash::check($new,$row->password_hash))return response()->json(['error'=>'Le nouveau mot de passe doit etre different du mot de passe temporaire.'],422);DB::table('users')->where('id',$u['id'])->update(['password_hash'=>Hash::make($new),'must_change_password'=>false]);return response()->json(['message'=>'Mot de passe securise. Premiere connexion validee.','user'=>$this->user($u['id'])]); }
    private function createUser(Request $r): JsonResponse { $emailEnabled=!in_array(config('mail.default'),['log','array'],true);$email=strtolower(trim((string)$r->email));if(!$r->name||!filter_var($email,FILTER_VALIDATE_EMAIL)||!in_array($r->role,['rh','manager','collaborateur','dg'],true))return response()->json(['error'=>'Nom, adresse email et role valides obligatoires.'],422);$allowedCategories=['collaborateur'=>['Employe','Technicien','Agent','Cadre'],'manager'=>['Cadre'],'dg'=>['Cadre dirigeant'],'rh'=>['Cadre']];$category=Str::ascii((string)($r->category??$allowedCategories[$r->role][0]));if(!in_array($category,$allowedCategories[$r->role],true))$category=$allowedCategories[$r->role][0];if(DB::table('users')->where('email',$email)->exists())return response()->json(['error'=>'Cette adresse email est deja utilisee.'],422);$direction=DB::table('directions')->where('name',$r->direction_name)->first();$filiale=DB::table('filiales')->where('name',$r->filiale_name)->first();$poste=DB::table('postes')->where('name',$r->poste_name)->first();if(!$poste&&$r->poste_name)$poste=(object)['id'=>DB::table('postes')->insertGetId(['name'=>$r->poste_name,'direction_id'=>$direction->id??DB::table('directions')->value('id')])];$temporary=(string)(env('DEFAULT_TEMP_PASSWORD')?:Str::password(14,true,true,true,false));$id=DB::table('users')->insertGetId(['name'=>$r->name,'email'=>$email,'role'=>$r->role,'poste_id'=>$poste->id??null,'filiale_id'=>$filiale->id??null,'direction_id'=>$direction->id??null,'manager_id'=>$r->manager_id?:null,'avatar'=>null,'password_hash'=>Hash::make($temporary),'must_change_password'=>true,'category'=>$category]);$link=rtrim(env('FRONTEND_URL','http://localhost:3000'),'/');if($emailEnabled){try{Mail::send('emails.new-user',['name'=>$r->name,'email'=>$email,'temporaryPassword'=>$temporary,'loginUrl'=>$link],fn($message)=>$message->to($email,$r->name)->subject('Bienvenue - Vos acces a Gestion Evaluation RH'));$this->recordNotification($id,'Creation de compte','Vos acces temporaires ont ete envoyes par email.','new_user','email',$link);}catch(\Throwable $mailError){DB::table('users')->where('id',$id)->delete();throw new \RuntimeException('L utilisateur n a pas ete cree car l email n a pas pu etre envoye. Verifiez la configuration Gmail ou SMTP.',0,$mailError);}}$message=$emailEnabled?'Utilisateur cree. Ses acces temporaires ont ete envoyes par email.':'Utilisateur cree. Mot de passe temporaire de test : Bienvenue#2026';return response()->json(['message'=>$message,'email_sent'=>$emailEnabled,'user'=>$this->user($id)],$emailEnabled?201:202); }
    private function userItem(Request $r,int $id): JsonResponse { if($r->isMethod('delete')){DB::table('users')->where('id',$id)->delete();return response()->json(['message'=>'Utilisateur supprime.']);} $d=$r->except(['id','password','password_hash','poste_name','filiale_name','direction_name','manager_name','avatar']); DB::table('users')->where('id',$id)->update($d); return response()->json($this->user($id)); }
    private function resendInvitation(int $id): JsonResponse {if(in_array(config('mail.default'),['log','array'],true))return response()->json(['error'=>'SMTP reel non configure. Invitation non renvoyee.'],503);$user=DB::table('users')->find($id);if(!$user)return response()->json(['error'=>'Utilisateur introuvable.'],404);$temporary=(string)(env('DEFAULT_TEMP_PASSWORD')?:Str::password(14,true,true,true,false));$link=rtrim(env('FRONTEND_URL','http://localhost:3000'),'/');Mail::send('emails.new-user',['name'=>$user->name,'email'=>$user->email,'temporaryPassword'=>$temporary,'loginUrl'=>$link],fn($message)=>$message->to($user->email,$user->name)->subject('Nouvelle invitation - Gestion Evaluation RH'));$this->recordNotification($id,'Nouvelle invitation','Une nouvelle invitation de connexion a ete envoyee par email.','new_user','email',$link);DB::table('users')->where('id',$id)->update(['password_hash'=>Hash::make($temporary),'must_change_password'=>true]);return response()->json(['message'=>'Une nouvelle invitation securisee a ete envoyee a '.$user->email.'.']);}
    private function campaigns(): array { return DB::table('campagnes')->orderByDesc('id')->get()->map(function($c){$a=(array)$c;foreach(['filiales','directions','categories','managers_informes'] as $k)$a[$k]=json_decode($a[$k]??'[]',true)?:[];return $a;})->all(); }
    private function saveCampaign(Request $r): JsonResponse { $d=$r->except('id'); foreach(['filiales','directions','categories','managers_informes'] as $k)if(array_key_exists($k,$d))$d[$k]=json_encode($d[$k]); $id=DB::table('campagnes')->insertGetId($d); return response()->json(collect($this->campaigns())->firstWhere('id',$id),201); }
    private function deleteCampaign(int $id): JsonResponse { $campaign=DB::table('campagnes')->find($id);if(!$campaign)return response()->json(['error'=>'Campagne introuvable.'],404);DB::table('revue_annuel')->where('campagne_id',$id)->delete();DB::table('audit_logs')->where('campagne_id',$id)->delete();DB::table('campagnes')->where('id',$id)->delete();return response()->json(['message'=>'Campagne supprimée avec succès.']); }
    private function campaignAction(Request $r,int $id,?string $action): JsonResponse {
        if(!$action){$d=$r->except('id');foreach(['filiales','directions','categories','managers_informes'] as $k)if(isset($d[$k]))$d[$k]=json_encode($d[$k]);DB::table('campagnes')->where('id',$id)->update($d);}
        else{$status=['launch'=>'ouverte','close'=>'cloturee','archive'=>'archivee','relaunch'=>'ouverte'][$action];DB::table('campagnes')->where('id',$id)->update(['status'=>$status]);}
        $c=collect($this->campaigns())->firstWhere('id',$id);
        if($action==='launch'&&$c){
            $collaborators=DB::table('users as u')->leftJoin('postes as p','p.id','=','u.poste_id')->leftJoin('filiales as f','f.id','=','u.filiale_id')->leftJoin('directions as d','d.id','=','u.direction_id')->leftJoin('users as m','m.id','=','u.manager_id')->where('u.role','collaborateur')->select('u.*','p.name as poste_name','f.name as filiale_name','d.name as direction_name','m.name as manager_name')->get();
            foreach($collaborators as $user){if(DB::table('revue_annuel')->where('campagne_id',$id)->where('user_id',$user->id)->exists())continue;$templates=DB::table('competence_templates as ct')->join('fiches_evaluation as fe','fe.id','=','ct.fiche_id')->where('fe.poste_id',$user->poste_id)->select('ct.id','ct.axe','ct.name','ct.description','ct.coefficient')->orderBy('ct.id')->get();$competences=$templates->map(fn($t)=>['id'=>(int)$t->id,'competence_id'=>(int)$t->id,'evaluation_id'=>0,'axe'=>$t->axe,'name'=>$t->name,'description'=>$t->description,'coefficient'=>(float)$t->coefficient,'score'=>0,'comment'=>''])->all();$payload=['campagne_id'=>$id,'campagne_name'=>$c['name'],'user_id'=>(int)$user->id,'user_name'=>$user->name,'user_avatar'=>'','user_category'=>$user->category,'poste_name'=>$user->poste_name??'','filiale_name'=>$user->filiale_name??'','direction_name'=>$user->direction_name??'','manager_id'=>(int)($user->manager_id??0),'manager_name'=>$user->manager_name??'','status'=>'en_attente','score_savoir'=>0,'score_savoir_faire'=>0,'score_savoir_etre'=>0,'score_global'=>0,'competences'=>$competences,'besoins_formation'=>[],'axes_developpement'=>[],'objectifs'=>[]];$evaluationId=DB::table('revue_annuel')->insertGetId(['campagne_id'=>$id,'campagne_name'=>$c['name'],'user_id'=>$user->id,'user_name'=>$user->name,'manager_id'=>$user->manager_id??0,'manager_name'=>$user->manager_name??'','filiale_name'=>$user->filiale_name??'','direction_name'=>$user->direction_name??'','status'=>'en_attente','score_global'=>0,'payload'=>json_encode($payload,JSON_UNESCAPED_UNICODE)]);$payload['id']=$evaluationId;foreach($payload['competences'] as &$competence)$competence['evaluation_id']=$evaluationId;unset($competence);DB::table('revue_annuel')->where('id',$evaluationId)->update(['payload'=>json_encode($payload,JSON_UNESCAPED_UNICODE)]);}
            $recipients=DB::table('users')->whereIn('role',['collaborateur','manager','dg'])->pluck('id');foreach($recipients as $userId)$this->notifyEmail((int)$userId,'Nouvelle campagne d evaluation','La campagne "'.$c['name'].'" est ouverte. Periode : '.($c['start_date']??'').' au '.($c['end_date']??'').'. Dates importantes : auto-evaluation jusqu au '.($c['auto_eval_deadline']??'').', evaluation manager jusqu au '.($c['manager_eval_deadline']??'').', validation DG jusqu au '.($c['dg_validation_deadline']??'').'.','campaign_launch',$this->notificationLink('campaigns'));
        }
        return response()->json($action?['message'=>'Campagne mise a jour.','campagne'=>$c]:$c);
    }
    private function decode($row): array { $a=json_decode($row->payload,true)?:[]; return array_merge($a,['id'=>(int)$row->id,'campagne_id'=>(int)$row->campagne_id,'user_id'=>(int)$row->user_id,'manager_id'=>(int)$row->manager_id,'status'=>$row->status,'score_global'=>(float)$row->score_global]); }
    private function evaluations(Request $r): array { $q=DB::table('revue_annuel'); foreach(['user_id','manager_id','campagne_id','status'] as $k)if($r->query($k)!==null)$q->where($k,$r->query($k));$actor=$this->actor($r);if(($actor['role']??null)==='dg'&&!empty($actor['direction_name']))$q->where('direction_name',$actor['direction_name']); return $q->orderByDesc('id')->get()->map(fn($x)=>$this->decode($x))->all(); }
    private function saveEvaluation(Request $r,?int $id=null): JsonResponse { $d=$r->all(); $cols=['campagne_id'=>$d['campagne_id']??0,'campagne_name'=>$d['campagne_name']??'','user_id'=>$d['user_id']??0,'user_name'=>$d['user_name']??'','manager_id'=>$d['manager_id']??0,'manager_name'=>$d['manager_name']??'','filiale_name'=>$d['filiale_name']??'','direction_name'=>$d['direction_name']??'','status'=>$d['status']??'en_attente','score_global'=>$d['score_global']??0,'payload'=>json_encode(array_diff_key($d,['id'=>1]),JSON_UNESCAPED_UNICODE)]; if($id)DB::table('revue_annuel')->where('id',$id)->update($cols);else$id=DB::table('revue_annuel')->insertGetId($cols); return response()->json($this->decode(DB::table('revue_annuel')->find($id)),$id?200:201); }
    private function evaluationAction(Request $r,int $id,string $action): JsonResponse { $row=DB::table('revue_annuel')->find($id);if(!$row)return response()->json(['error'=>'Evaluation introuvable.'],404);if(!$action&&$r->isMethod('get'))return response()->json($this->decode($row));if($r->isMethod('delete')&&!$action){DB::table('revue_annuel')->where('id',$id)->delete();return response()->json(['message'=>'Evaluation supprimee.']);}if(!$action){$incoming=$r->all();$current=$this->decode($row);$actor=$this->actor($r);if(($actor['role']??null)==='manager'&&isset($incoming['competences'])){$submitted=collect($incoming['competences'])->keyBy('id');$incoming['competences']=collect($current['competences']??[])->map(function($original)use($submitted){$scores=$submitted->get($original['id'],[]);return array_merge($original,['score'=>$scores['score']??$original['score']??0,'comment'=>$scores['comment']??$original['comment']??'']);})->values()->all();}return $this->saveEvaluation(new Request($incoming),$id);}$e=$this->decode($row);
        if(str_starts_with($action,'competences')&&($this->actor($r)['role']??null)!=='rh')return response()->json(['error'=>'Seul le DRH peut ajouter ou supprimer une competence.'],403);
        if(preg_match('#^(competences|training|objectives|improvements)(?:/(\d+))?$#',$action,$m)){ $key=['competences'=>'competences','training'=>'besoins_formation','objectives'=>'objectifs','improvements'=>'axes_developpement'][$m[1]]; $items=$e[$key]??[]; if($r->isMethod('delete'))$items=array_values(array_filter($items,fn($x)=>(int)($x['id']??0)!==(int)$m[2])); else {$item=$r->all();$item['id']=count($items)?max(array_map(fn($x)=>(int)($x['id']??0),$items))+1:1;$item['evaluation_id']=$id;$items[]=$item;} $e[$key]=$items; return $this->saveEvaluation(new Request($e),$id); }
        if($action==='auto-eval'){$comments=$r->input('comments',[]);foreach(($e['competences']??[]) as $competence){if(empty(trim((string)($comments[(string)($competence['id']??'')]??''))))return response()->json(['error'=>'Un commentaire collaborateur est obligatoire pour chaque competence.'],422);}$e['auto_evaluation']=['evaluation_id'=>$id,'user_id'=>$e['user_id'],'balance'=>$r->input('balance',''),'achievements'=>$r->input('achievements',''),'difficulties'=>$r->input('difficulties',''),'aspirations'=>$r->input('aspirations',''),'ratings'=>$r->input('ratings',[]),'comments'=>$comments,'submitted_at'=>now()->toISOString()];$e['status']='auto_eval_terminee';$this->saveEvaluation(new Request($e),$id);if(!empty($e['manager_id']))$this->notifyPlatform((int)$e['manager_id'],'Auto-evaluation recue',($e['user_name']??'Un collaborateur').' a termine et transmis son auto-evaluation.','auto_evaluation_submitted');return response()->json(['message'=>'Auto-evaluation transmise au manager.','evaluation'=>$this->decode(DB::table('revue_annuel')->find($id))]);}
        if($action==='submit'&&empty($e['interview_date']))return response()->json(['error'=>'Planifiez d abord l entretien avec le collaborateur avant de soumettre a la DG.'],422);
        if(in_array($action,['submit','submit-correction'],true))foreach(($e['competences']??[]) as $competence){if(empty(trim((string)($competence['comment']??''))))return response()->json(['error'=>'Un commentaire manager est obligatoire pour chaque competence avant la soumission.'],422);}
        $previousStatus=$e['status']??'';$map=['interview'=>'entretien_planifie','submit'=>'soumis_dg','submit-correction'=>'correction_a_confirmer','confirm-correction'=>'correction_a_confirmer','sign'=>'signee'];$e=array_merge($e,$r->all());if($action==='interview')$e['interview_message']=$r->input('message','Votre Manager a planifie un entretien.');if($action==='submit-correction')$e['manager_correction_submitted_at']=now()->toISOString();if($action==='sign'){$e['signed_at_user']=now()->toISOString();$e['status']='signee';}elseif($action==='validate-dg')$e['status']=$r->action==='renvoyer'?'a_corriger':'validee';elseif(isset($map[$action]))$e['status']=$map[$action];$this->saveEvaluation(new Request($e),$id);
        if($action==='interview')$this->notifyEmail((int)$e['user_id'],'Entretien d evaluation planifie',($e['interview_message']??'Votre Manager a planifie un entretien.').' Date et heure : '.($e['interview_date']??'').'.','interview_scheduled',$this->notificationLink('my_eval'));
        if($action==='submit')foreach($this->dgRecipientsForEvaluation($e) as $dgId)$this->notifyEmail((int)$dgId,'Evaluation a valider','Le dossier de '.($e['user_name']??'un collaborateur').' est en attente de votre decision.','evaluation_submitted_dg',$this->notificationLink('dg_queue'));
        if($action==='submit-correction')foreach($this->dgRecipientsForEvaluation($e) as $dgId)$this->notifyPlatform((int)$dgId,'Correction terminee par le manager','Le manager '.($e['manager_name']??'concerné').' a termine la verification et les corrections du dossier de '.($e['user_name']??'un collaborateur').'. Le dossier sera disponible pour validation finale apres signature du collaborateur.','correction_ready',$this->notificationLink('dg_queue'));
        if($action==='confirm-correction')$this->notifyPlatform((int)$e['manager_id'],'Correction confirmee par le collaborateur','Le collaborateur '.($e['user_name']??'').' a confirme la correction. Le dossier attend sa signature avant transmission a la DG.','correction_confirmed');
if($action==='validate-dg'){if($r->action==='renvoyer'){$this->notifyEmail((int)$e['manager_id'],'Dossier a corriger','La Direction Generale demande une correction du dossier de '.($e['user_name']??'un collaborateur').'. Commentaire : '.($r->comment??'').'. Delai accorde : 72 heures.','dg_correction_requested',$this->notificationLink('manager_team'));}else{$rhIds=DB::table('users')->where('role','rh')->pluck('id')->map(fn($x)=>(int)$x)->all();foreach(array_filter(array_merge([(int)$e['manager_id'],(int)$e['user_id']],$rhIds)) as $recipient)$this->notifyEmail($recipient,'Evaluation validee definitivement','L evaluation de '.($e['user_name']??'').' a ete validee avec succes. Le processus est termine.','evaluation_validated',$this->notificationLink());}}
        if($action==='sign'&&!empty($e['manager_id'])){$this->notifyPlatform((int)$e['manager_id'],'Evaluation signee par le collaborateur','Le collaborateur '.($e['user_name']??'').' a confirme la reception de son evaluation.','evaluation_signed',$this->notificationLink('manager_team'));foreach($this->dgRecipientsForEvaluation($e) as $dgId)$this->notifyPlatform((int)$dgId,'Dossier signe a valider','Le collaborateur '.($e['user_name']??'').' a signe son evaluation. Le dossier est disponible pour validation finale.','evaluation_signed',$this->notificationLink('dg_queue'));}
        return response()->json(['message'=>'Action enregistree et notifications envoyees.','evaluation'=>$this->decode(DB::table('revue_annuel')->find($id))]); }
    private function importJobTemplates(Request $r): JsonResponse {
        $models=$r->input('models',[]);if(!is_array($models)||count($models)===0)return response()->json(['error'=>'Le fichier Excel ne contient aucune fiche exploitable.'],422);
        $result=DB::transaction(function()use($models){$direction=DB::table('directions')->where('name','Direction non affectee')->first();if(!$direction){$directionId=DB::table('directions')->insertGetId(['name'=>'Direction non affectee','code'=>'NA']);}else{$directionId=$direction->id;}$fiches=0;$criteriaCount=0;$postesCreated=0;
            foreach($models as $model){$posteName=trim((string)($model['poste_name']??''));$criteria=$model['criteria']??[];if($posteName===''||!is_array($criteria)||count($criteria)===0)continue;$poste=DB::table('postes')->whereRaw('LOWER(name) = ?', [mb_strtolower($posteName)])->first();if(!$poste){$posteId=DB::table('postes')->insertGetId(['name'=>$posteName,'direction_id'=>$directionId]);$postesCreated++;}else{$posteId=$poste->id;}$fiche=DB::table('fiches_evaluation')->where('poste_id',$posteId)->first();if(!$fiche){$ficheId=DB::table('fiches_evaluation')->insertGetId(['name'=>'Fiche d evaluation - '.$posteName,'poste_id'=>$posteId,'description'=>'Modele importe depuis le fichier Excel DRH.']);}else{$ficheId=$fiche->id;DB::table('fiches_evaluation')->where('id',$ficheId)->update(['name'=>'Fiche d evaluation - '.$posteName,'updated_at'=>now()]);}DB::table('competence_templates')->where('fiche_id',$ficheId)->delete();foreach($criteria as $criterion){$axe=$criterion['axe']??'';if(!in_array($axe,['savoir','savoir_faire','savoir_etre'],true)||empty($criterion['name']))continue;DB::table('competence_templates')->insert(['fiche_id'=>$ficheId,'axe'=>$axe,'name'=>$criterion['name'],'description'=>$criterion['description']??'','coefficient'=>(float)($criterion['coefficient']??1)]);$criteriaCount++;}$fiches++;}return ['fiches'=>$fiches,'criteres'=>$criteriaCount,'postes_crees'=>$postesCreated];});
        return response()->json(['message'=>'Import Excel termine.','result'=>$result]);
    }

    private function kpis(): JsonResponse {
        $campaign=DB::table('campagnes')->where('status','ouverte')->orderByDesc('id')->first() ?: DB::table('campagnes')->orderByDesc('id')->first();
        $rows=DB::table('revue_annuel')->when($campaign,fn($q)=>$q->where('campagne_id',$campaign->id))->get()->map(fn($r)=>$this->decode($r));
        $total=$rows->count(); $completed=$rows->filter(fn($e)=>in_array($e['status'],['valide','validee','soumis_dg','signee']))->count(); $validated=$rows->filter(fn($e)=>in_array($e['status'],['valide','validee']))->count();
        $average=function($items){$scored=$items->filter(fn($e)=>(float)($e['score_global']??0)>0);return ['average'=>$scored->count()?round($scored->avg(fn($e)=>(float)$e['score_global']),1):0,'evaluated'=>$scored->count(),'total'=>$items->count()];};
        $groupAverage=function($field,$label)use($rows,$average){return $rows->filter(fn($e)=>!empty($e[$field]))->groupBy($field)->map(fn($items,$name)=>array_merge([$label=>$name],$average($items)))->values()->all();};
        $managers=DB::table('users as u')->leftJoin('directions as d','d.id','=','u.direction_id')->where('u.role','manager')->select('u.id','u.name','d.name as direction')->get();
        $managerDelays=$managers->map(function($m)use($rows){$items=$rows->where('manager_id',(int)$m->id);$late=$items->filter(fn($e)=>in_array($e['status'],['en_attente','auto_eval_terminee','auto_evaluation_validee','en_cours_manager','entretien_planifie']))->count();return ['manager_name'=>$m->name,'direction'=>$m->direction??'','late_count'=>$late,'total_count'=>$items->count()];})->all();
        $competences=$rows->flatMap(fn($e)=>$e['competences']??[])->filter(fn($c)=>(float)($c['score']??0)>0)->groupBy(fn($c)=>($c['axe']??'').'|'.($c['name']??''))->map(fn($items)=>['name'=>$items->first()['name']??'','axe'=>$items->first()['axe']??'','score'=>round($items->avg(fn($c)=>(float)$c['score']),1)])->values();
        $axes=['savoir'=>'Savoir','savoir_faire'=>'Savoir-faire','savoir_etre'=>'Savoir-etre']; $axisAverages=[];foreach($axes as $key=>$label){$values=$rows->pluck('score_'.$key)->filter(fn($v)=>(float)$v>0);$axisAverages[]=['axis'=>$label,'weight'=>['savoir'=>'20%','savoir_faire'=>'50%','savoir_etre'=>'30%'][$key],'score'=>$values->count()?round($values->avg(),1):0];}
        $training=$rows->flatMap(fn($e)=>$e['besoins_formation']??[])->groupBy(fn($n)=>$n['title']??'Autre')->map(fn($items,$name)=>['category'=>$name,'count'=>$items->count(),'highPriority'=>$items->where('priority','Haute')->count()])->values()->all();
        return response()->json(['globalProgress'=>$total?round($completed*100/$total):0,'totalEvaluations'=>$total,'completedEvaluations'=>$completed,'pendingEvaluations'=>$total-$completed,'validatedEvaluations'=>$validated,'managerDelays'=>$managerDelays,'filialeAverages'=>$groupAverage('filiale_name','filiale'),'directionAverages'=>$groupAverage('direction_name','direction'),'familyAverages'=>$groupAverage('direction_name','family'),'functionAverages'=>$groupAverage('poste_name','function'),'axisAverages'=>$axisAverages,'scoreDistribution'=>[['range'=>'< 60% (Insuffisant)','count'=>$rows->filter(fn($e)=>($e['score_global']??0)>0&&$e['score_global']<60)->count()],['range'=>'60% - 75% (Moyen)','count'=>$rows->filter(fn($e)=>($e['score_global']??0)>=60&&$e['score_global']<75)->count()],['range'=>'75% - 90% (Satisfaisant)','count'=>$rows->filter(fn($e)=>($e['score_global']??0)>=75&&$e['score_global']<90)->count()],['range'=>'90% - 100% (Excellent)','count'=>$rows->filter(fn($e)=>($e['score_global']??0)>=90)->count()]],'topCompetencies'=>$competences->sortByDesc('score')->take(4)->values(),'weakCompetencies'=>$competences->sortBy('score')->take(3)->values(),'trainingNeedsSummary'=>$training]);
    }
}
